// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package googleendpointsservice

import (
	"github.com/open-constructs/cdk-terrain-go/cdktn"
)

type GoogleEndpointsServiceConfig struct {
	// Experimental.
	Connection interface{} `field:"optional" json:"connection" yaml:"connection"`
	// Experimental.
	Count interface{} `field:"optional" json:"count" yaml:"count"`
	// Experimental.
	DependsOn *[]cdktn.ITerraformDependable `field:"optional" json:"dependsOn" yaml:"dependsOn"`
	// Experimental.
	ForEach cdktn.ITerraformIterator `field:"optional" json:"forEach" yaml:"forEach"`
	// Experimental.
	Lifecycle *cdktn.TerraformResourceLifecycle `field:"optional" json:"lifecycle" yaml:"lifecycle"`
	// Experimental.
	Provider cdktn.TerraformProvider `field:"optional" json:"provider" yaml:"provider"`
	// Experimental.
	Provisioners *[]interface{} `field:"optional" json:"provisioners" yaml:"provisioners"`
	// The name of the service. Usually of the form $apiname.endpoints.$projectid.cloud.goog.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/google-beta/7.36.0/docs/resources/google_endpoints_service#service_name GoogleEndpointsService#service_name}
	ServiceName *string `field:"required" json:"serviceName" yaml:"serviceName"`
	// Whether Terraform will be prevented from destroying the instance.
	//
	// Defaults to "DELETE".
	// When a 'terraform destroy' or 'terraform apply' would delete the instance,
	// the command will fail if this field is set to "PREVENT" in Terraform state.
	// When set to "ABANDON", the command will remove the resource from Terraform
	// management without updating or deleting the resource in the API.
	// When set to "DELETE", deleting the resource is allowed.
	//
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/google-beta/7.36.0/docs/resources/google_endpoints_service#deletion_policy GoogleEndpointsService#deletion_policy}
	DeletionPolicy *string `field:"optional" json:"deletionPolicy" yaml:"deletionPolicy"`
	// The full text of the Service Config YAML file (Example located here).
	//
	// If provided, must also provide protoc_output_base64. open_api config must not be provided.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/google-beta/7.36.0/docs/resources/google_endpoints_service#grpc_config GoogleEndpointsService#grpc_config}
	GrpcConfig *string `field:"optional" json:"grpcConfig" yaml:"grpcConfig"`
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/google-beta/7.36.0/docs/resources/google_endpoints_service#id GoogleEndpointsService#id}.
	//
	// Please be aware that the id field is automatically added to all resources in Terraform providers using a Terraform provider SDK version below 2.
	// If you experience problems setting this value it might not be settable. Please take a look at the provider documentation to ensure it should be settable.
	Id *string `field:"optional" json:"id" yaml:"id"`
	// The full text of the OpenAPI YAML configuration as described here.
	//
	// Either this, or both of grpc_config and protoc_output_base64 must be specified.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/google-beta/7.36.0/docs/resources/google_endpoints_service#openapi_config GoogleEndpointsService#openapi_config}
	OpenapiConfig *string `field:"optional" json:"openapiConfig" yaml:"openapiConfig"`
	// The project ID that the service belongs to. If not provided, provider project is used.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/google-beta/7.36.0/docs/resources/google_endpoints_service#project GoogleEndpointsService#project}
	Project *string `field:"optional" json:"project" yaml:"project"`
	// The full contents of the Service Descriptor File generated by protoc. This should be a compiled .pb file, base64-encoded.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/google-beta/7.36.0/docs/resources/google_endpoints_service#protoc_output_base64 GoogleEndpointsService#protoc_output_base64}
	ProtocOutputBase64 *string `field:"optional" json:"protocOutputBase64" yaml:"protocOutputBase64"`
	// timeouts block.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/google-beta/7.36.0/docs/resources/google_endpoints_service#timeouts GoogleEndpointsService#timeouts}
	Timeouts *GoogleEndpointsServiceTimeouts `field:"optional" json:"timeouts" yaml:"timeouts"`
}

